[google]
type = "service_account"
project_id = "tailortalkbot-464606"
private_key_id = "1b1b4877c879fb814b2b3f765aa7f49323500264"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqXbl1gNibRF66
IjxoEBQReg1U2J8caYdtSZpZKn+NOf8XxAmv9xXWVVlHX9wYtmRWRWakOsZyhU/k
LSjRoU6PATXxStA0YWsMJMdGgFPinB7s01OcSWdKuhFL7qU/9+hraDkPsn0Yt0wY
4tCzthFGQVOehwzMMZzsHkBHZtowXv8GqpwYCOTSJQsP4KJbPX5GOUodAin6nkbs
YIer6xOHoESKoIrPku7BJwJC54DRulsDHhekJfa/6ErAvvDgyqqdPTSGcWJ4ygg+
Tsig7vFUs6O7udcyLCDrsOzKxVkU5w5dxyIEtWavYurtkeaiyoAKH9kfZLD/E5yp
Y9yGcmn9AgMBAAECggEAFvc0cXERgfi49kl4MCT+t45m7qmW5UsafPJ/koaGlECd
sRP1pFlgAbkWpGb5MgGgS/rmB7x+lOCAsQcfagbfIqrsnR7TK0R4nDX3APt6k2Et
UAp6ymYgvPORMlW0xAdEtvnhO0r5zxOid/ZXYOppsLlMruGQqZQEjdXUH2vvfLaR
E9pLI0hp2oLeqh068/gCh91pvJ8DiTQN2AXQkJuKlQWVRsB2wpTmCuezADUYCkda
8PYl+sWbuWAM7qAShuCjR8PVToQiOX8TQDUXSOyNd1eTSE/BgqTg64o6nwt9QVw4
20pZgVrSN46Y/OAvhqUQp0BMXSejYL3ChH0I+211kQKBgQDjQTfTyZ90M4/BefNk
rFH9Yq28DxdCkH2dYcC2wRO1TEW17u32/RUws4pk7YwMF3i5FThue2Wr/e2t9iNr
uwsliDgy8chr/2AjvMau+PAQPvwwScmODJ7pR6lP+MO/Qs5L9YbD9nzXAFgCM6df
SuKv0vssLhbHafZRJgjHev9aiQKBgQC/6mI44YOARPbgvwi5VpG3oW9fHDI2ajY/
vj4lQg9VDwc1rn8zSHQEVC3SlPljvG7F1mTYCEPZXrlGM8BjqmbFtE30V6odan8C
iGOtDIITwTP95uPQ7+6uP0krR4GKnKnI1v8o7ymMh10Sq/GsqBVFJOdIp0vW8GdH
8ROrIj3m1QKBgE3JyDNNg7BB6gY/GSovtgz21yNVQw/855KUoGOuKXHYftAszfXK
YZN/EXNEwLhu3Fr2QY/H22CJFe+DHlLE/qbFPv9pNcKJ8r2o45WHDp1xAeABkeV2
unp9lh4St+ZjFrx3eb7gQ5FQw89VIQiEWJ34qRNRX2i5A6B5VW360yeJAoGARIVD
snlaASceWhn63Gl7N2wNHpEroGAFpHahK55NaRongdQemEnLGmyPu7ry29hAWKR2
dudkiiyWy+jYTP1fGkGI/695Dm2ikV3u8K8hljoJ/SI9vrCbsFzqG+i46KuMtyeE
DLJvTDxcT7lSXUnZ5kkJxtfsbP6CcZ4yXoyoO00CgYEAzIeAUvXXBk65kWnSw56o
trGWJngF+GHsHu7lfRldELKmepLV4Pi565V0BSsKvd21PvUltuCq4njfQBY9Q4aL
quhZAhNQ04wCRPyW2gOBWdFyjnNYs711aq8oV/xtLWpSjvcPHB5TiglyETcgvetl
y0VQyCfPsv3bhgDwGPmAiFo=
-----END PRIVATE KEY-----"""
client_email = "tailortalk-bot@tailortalkbot-464606.iam.gserviceaccount.com"
client_id = "109917769022349398616"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tailortalk-bot%40tailortalkbot-464606.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


[general] 

OPENROUTER_API_KEY = "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"

